<!DOCTYPE html>

<!--
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 4 & Angular 8
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Dribbble: www.dribbble.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
Renew Support: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<?php
    $conf = $this->serviceManager()->get('Config')['metronic'];
    $variant = $conf['variant'];

    if (empty($variant)) {
        $variant = 'demo1';
    }
    $asideClass = empty($this->aside) ? '' : ' aside-enabled aside-fixed';
?>
<html lang="en" style="overflow-x: hidden">
<!-- BEGIN HEAD -->

<head>
    <base href="">
    <meta charset="utf-8"/>
    <?php
        echo $this->navigation('default')->breadcrumbs()->setUseAcl(false)->setPartial(['navigation/partial/breadcrumbs-window-title', 'default']);
        echo $this->headTitle();
    ?>
    <meta name="description" content="Product information management">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--begin::Fonts-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700"/>

    <!--end::Fonts-->

    <!--begin::Page Vendors Styles(used by this page)-->
    <!--<link href="/assets/plugins/custom/fullcalendar/fullcalendar.bundle.css?v=7.0.3" rel="stylesheet" type="text/css" />-->
    <!--end::Page Vendors Styles-->

    <!--begin::Global Theme Styles(used by all pages)-->
    <link href="/assets/plugins/global/plugins.bundle.css?v=7.0.3" rel="stylesheet" type="text/css"/>
    <!--<link href="/assets/plugins/custom/prismjs/prismjs.bundle.css?v=7.0.3" rel="stylesheet" type="text/css" />-->
    <link href="/assets/css/style.bundle.css?v=7.0.3" rel="stylesheet" type="text/css"/>

    <!--end::Global Theme Styles-->

    <!--begin::Layout Themes(used by all pages)-->
    <link href="/assets/css/themes/layout/header/base/dark.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/css/themes/layout/header/menu/light.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/css/themes/layout/brand/dark.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/css/themes/layout/aside/light.css" rel="stylesheet" type="text/css"/>

    <?php echo $this->headLink() ?>
    <!--end::Layout Skins -->
    <?= $this->render("logo/favicon"); ?>
    <link href="/css/custom.css" rel="stylesheet" type="text/css"/>
    <!-- END HEAD -->
</head>
<!--subheader-fixed header-fixed header-mobile-fixed-->
<body id="kt_body" class="subheader-enabled subheader-fixed header-fixed header-mobile-fixed page-loading<?php echo $asideClass ?>"<?php echo devhelp(__FILE__) ?>>
<!-- begin:: Page -->

<!--[html-partial:include:{"file":"partials/_header/base-mobile.html"}]/-->
<?php
$file = __DIR__ . "/layout/layout-$variant.phtml";
if (file_exists($file)) {
    echo $this->render("layout/layout-$variant.phtml");
} else {
    echo $this->render("layout/layout-default.phtml");
}
?>


<!--[html-partial:include:{"file":"partials/_quick-panel.html"}]/-->

<!--[html-partial:include:{"file":"partials/_scrolltop.html"}]/-->

<!--[html-partial:include:{"file":"partials/_toolbar.html"}]/-->

<!--[html-partial:include:{"file":"partials/_demo-panel.html"}]/-->

<!--[html-partial:include:{"file":"partials/_chat.html"}]/-->
<div id="ajax-modal" class="modal fade" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

        </div>
    </div>
</div>

<?php
    //echo $this->render('toolbar/sticky-toolbar')?>


<!-- begin::Global Config(global config for global JS sciprts) -->
<!--end::Demo Panel-->
<script>//var HOST_URL = "https://keenthemes.com/metronic/tools/preview";</script>
<!--begin::Global Config(global config for global JS scripts)-->
<script>
    var KTAppSettings = {
        "breakpoints": {"sm": 576, "md": 768, "lg": 992, "xl": 1200, "xxl": 1200},
        "colors": {
            "theme": {
                "base": {
                    "white": "#ffffff",
                    "primary": "#3699FF",
                    "secondary": "#E5EAEE",
                    "success": "#1BC5BD",
                    "info": "#8950FC",
                    "warning": "#FFA800",
                    "danger": "#F64E60",
                    "light": "#F3F6F9",
                    "dark": "#212121"
                },
                "light": {
                    "white": "#ffffff",
                    "primary": "#E1F0FF",
                    "secondary": "#ECF0F3",
                    "success": "#C9F7F5",
                    "info": "#EEE5FF",
                    "warning": "#FFF4DE",
                    "danger": "#FFE2E5",
                    "light": "#F3F6F9",
                    "dark": "#D6D6E0"
                },
                "inverse": {
                    "white": "#ffffff",
                    "primary": "#ffffff",
                    "secondary": "#212121",
                    "success": "#ffffff",
                    "info": "#ffffff",
                    "warning": "#ffffff",
                    "danger": "#ffffff",
                    "light": "#464E5F",
                    "dark": "#ffffff"
                }
            },
            "gray": {
                "gray-100": "#F3F6F9",
                "gray-200": "#ECF0F3",
                "gray-300": "#E5EAEE",
                "gray-400": "#D6D6E0",
                "gray-500": "#B5B5C3",
                "gray-600": "#80808F",
                "gray-700": "#464E5F",
                "gray-800": "#1B283F",
                "gray-900": "#212121"
            }
        },
        "font-family": "Poppins"
    };
</script>
<!--end::Global Config-->
<!--begin::Global Theme Bundle(used by all pages)-->
<script src="/assets/plugins/global/plugins.bundle.js"></script>
<script src="/assets/js/scripts.bundle.js"></script>
<!--end::Global Theme Bundle-->
<!--begin::Page Vendors(used by this page)-->
<script src="/assets/plugins/custom/fullcalendar/fullcalendar.bundle.js"></script>
<!--end::Page Vendors-->
<!--begin::Page Scripts(used by this page)-->
<script src="/assets/js/pages/widgets.js"></script>
<!--<script src="/js/tab.handler.js" type="text/javascript"></script>-->
<!--end::Page Scripts-->
<script>
   $(document).ready(function () {
        $.ajaxSetup({
//                timeout: 5000,
            error: function (event, request, settings) {
                $('#ajax-modal').removeData('bs.modal').html('<?php echo $this->escapeJs($this->render('modal/error')) ?>');
            }
        });
    });

   $(document).ready(function(){
       $("#ajax-modal").on("show.bs.modal", function(event){
           var $activeLink = $(event.relatedTarget);
           $activeLink.parents('tr:first').addClass('table-active');
           $(this).find('.modal-content').load($activeLink.attr("href"));
       });
       $("#ajax-modal").on("hide.bs.modal", function(event){
           $('.dataTable tr.table-active').removeClass('table-active');
       });
       //$(".select2").select2( theme: 'bootstrap4');
       $(".select2").select2({
           width: 'element',
           allowClear: true,
           placeholder: "please select"
       });
   });
</script>
<?php echo $this->headScript(); ?>
<?php echo $this->inlineScript() ?>
<!--end::Page Scripts -->
</body>
</html>
