version: "3.8"
services:

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - elk

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch

  cerebro:
    image: lmenezes/cerebro
    environment:
      - CEREBRO_PORT=9201
    ports:
      - "9201:9201"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
  ws:

#  databases:
#    driver: bridge

volumes:
  elasticsearch-data:
