version: "3.8"
services:

  nginx:
    image: nginx:latest
    container_name: mng_nginx
    ports:
      - 8080:80
    volumes:
      - ./:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - php
    networks:
      - elk

  php:
    build:
      context: ./docker/php-fpm
    #container_name: mng_php
    ports:
      - 9000:9000
    volumes:
      - ./:/usr/share/nginx/html
      - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    restart: always
    networks:
      - elk

  adminer:
    build:
      context: ./docker/adminer
    restart: always
    ports:
      - 8083:8080
    networks:
    - elk

  mysql:
    image: mysql:latest
    volumes:
      - ./docker/mysql/mysql:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test123Pa
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
    ports:
      - 3306:3306
    networks:
      - elk

  #  redis:
  #    image: redis
  #    container_name: redis
  #    restart: always
  #    volumes:
  #      - ./docker/redis/redisdata:/data
  #      #- ./docker/redis-data:/var/lib/redis
  #      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
  #    ports:
  #      - 6379:6379
  #  #  logging:
  #   #   driver: none
  #    networks:
  #      - elk

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk
  #
  #  logstash:
  #    container_name: logstash
  #    build:
  #      context: ./docker/logstash
  #      args:
  #        ELK_VERSION: 7.9.1
  #    volumes:
  #      - ./docker/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
  #      - ./docker/logstash/pipeline:/usr/share/logstash/pipeline
  #    ports:
  #      - "5000:5000"
  #      - "9600:9600"
  #    environment:
  #      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
  #    networks:
  #      - elkrpc
  #    depends_on:
  #      - elasticsearch
  #
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.9.1
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch
#
#  cerebro:
#    container_name: cerebro
#    image: lmenezes/cerebro
#    restart: always
#    environment:
#      - CEREBRO_PORT=9201
#    ports:
#      - "9201:9201"
#    networks:
#      - elk
#    depends_on:
#      - elasticsearch

networks:
  elk:

#  databases:
#    driver: bridge

volumes:
  elasticsearch-data:
