<?php
/**
 * File element-group.phtml
 *
 * since: 19.10.2020
 * author: alexej@kisselev.de
 */

use Laminas\Form\ElementInterface;

$elements = $this->elements;
if (empty($elements)) {
    return;
}
$name = $this->translate($this->name);

/** @var ElementInterface $elementClone */
$elementClone = clone $elements[0];
$extended = $elementClone->getOption('extended');
$wrapClass = $extended['wrap']['class'] ?? 'col-lg-6';
$elementClone->setLabel($name);

?>
<div class="form-group row">
    <?php
    echo $this->formLabel($elementClone);
    ?>
    <div class="<?= $wrapClass ?> form-row row-eq-height">
        <?php
        /** @var ElementInterface $element */
        foreach ($elements as $element) {
            $options = $element->getOptions();
            $options['label_attributes']['class'] = 'col-form-label text-left';
            $options['extended']['wrap']['class'] = 'col';
            $options['label'] = $element->getLabel();
            $element->setOptions($options);
            echo $this->formRow($element);
        }
        ?>
    </div>
</div>
