<?php

use Laminas\Form\Element;
use Psr\Container\ContainerInterface;
use User\Form\LoginForm;
use User\ModuleOptions;

$this->headTitle('Sign in');
/** @var LoginForm $form */
$form = $this->form;
$messages = $form->getMessages();
$isLoginError = $this->isLoginError;
/** @var ContainerInterface $sm */
$sm = $this->getServiceManager();
/** @var ModuleOptions $options */
$options = $sm->get(ModuleOptions::class);
$element = $form->get('csrf');
$message = $this->message;
?>

<!--begin::Login Sign in form-->
<div class="login-signin"<?php echo devhelp(__FILE__) ?>>
    <div class="mb-20">
        <h3><?= $this->translate('Sign In To Admin') ?></h3>
        <div class="text-muted font-weight-bold"><?= $this->translate('Enter your details to login to your account') ?>:</div>
    </div>
    <?php echo $this->render('messenger/flash'); ?>
    <?php
    if (!empty($message)) {
        echo $this->render('alert/message-error.phtml', ['message' => $message]);
    } elseif ($isLoginError) {
        $message = 'Authentication failed: check your user name and password';
        if ($options->isCsrfOn()) {
            $messages = $element->getMessages();
            if (!empty($messages)) {
                $message = implode('<br>', $messages);
            }
        }
        echo $this->render('alert/message-error.phtml', ['message' => $message . '!']);
    }
    ?>
    <form class="form" id="kt_login_signin_form" method="post">
        <?php if ($options->isCsrfOn()):
            /** @var Element $element */
            $value = $element->getValue();
            ?>
            <input type="hidden" name="csrf" value="<?php echo $element->getValue() ?>"/>
        <?php endif; ?>
        <div class="form-group mb-5 validated">
            <?php
            /** @var Element $element */
            $element = $form->get('email');
            $value = $element->getValue();
            ?>
            <input autocomplete="off" class="form-control h-auto form-control-solid py-4 px-8" name="email" placeholder="Email" type="text"
                   value="<?php echo $element->getValue() ?>"/>
            <?php echo $this->render('form/validation/error.phtml', ['element' => $element]); ?>
        </div>
        <div class="form-group mb-5 validated">
            <input class="form-control h-auto form-control-solid py-4 px-8" type="password" placeholder="Password" name="password"/>
            <?php echo $this->render('form/validation/error.phtml', ['element' => $form->get('password')]); ?>
        </div>
        <div class="form-group d-flex flex-wrap justify-content-between align-items-center">
            <div class="checkbox-inline">
                <label class="checkbox m-0 text-muted">
                    <input type="hidden" name="remember_me" value="0"/>
                    <input type="checkbox" name="remember_me" value="1"/>
                    <span></span>Remember me</label>
            </div>
            <?php if ($options->isResetPasswordOn()): ?>
                <a href="<?= $this->url('auth', ['action' => 'resetPassword']) ?>" id="kt_login_forgot" class="text-muted text-hover-primary"><?= $this->translate('Forget Password') ?></a>
            <?php endif; ?>
        </div>
        <button id="kt_login_signin_submit" class="btn btn-primary font-weight-bold px-9 py-4 my-3 mx-4"><?= $this->translate('Sign In') ?></button>
    </form>
    <?php if ($options->isRegistrationOn()): ?>
        <div class="mt-10">
            <span class="opacity-70 mr-4"><?= $this->translate('Don\'t have an account yet') ?>?</span>
            <a href="<?= $this->url('auth', ['action' => 'add']) ?>" id="kt_login_signup" class="text-muted text-hover-primary font-weight-bold"><?= $this->translate('Sign Up') ?>
                !</a>
        </div>
    <?php endif; ?>
</div>
<!--end::Login Sign in form-->