<?php
/**
 * File set-password.phtml
 *
 * since: 20.01.2021
 * author: alexej@kisselev.de
 */

use Laminas\Form\Element;
use Psr\Container\ContainerInterface;
use User\Form\PasswordResetForm;
use User\ModuleOptions;

$this->headTitle('Sign in');
/** @var PasswordResetForm $form */
$form = $this->form;
$messages = $form->getMessages();

/** @var ContainerInterface $sm */
$sm = $this->getServiceManager();
/** @var ModuleOptions $options */
$options = $sm->get(ModuleOptions::class);
$element = $form->get('csrf');
$message = $this->message;

$backURL = $this->url('auth', ['action' => 'login']);
?>

<div class="login-signin"<?php echo devhelp(__FILE__) ?>>
    <div class="mb-20">
        <h3><?= $this->translate('Reset password') ?></h3>
        <div class="text-muted font-weight-bold">
            <?= $this->translate('Please enter your new password') ?>.
        </div>
    </div>
    <?php echo $this->render('messenger/flash'); ?>
    <?php
    if (!empty($message)) {
        echo $this->render('alert/message-error.phtml', ['message' => $message]);
    }
    ?>
    <form class="form" id="kt_login_signin_form" method="post">
        <?php if ($options->isCsrfOn()):
            /** @var Element $element */
            $value = $element->getValue();
            ?>
            <input type="hidden" name="csrf" value="<?php echo $element->getValue() ?>"/>
        <?php endif; ?>
        <div class="form-group mb-5 validated">
            <?php
            /** @var Element $element */
            $element = $form->get('new_password');
            ?>
            <input autocomplete="off" class="form-control h-auto form-control-solid py-4 px-8" name="new_password" placeholder="New password" type="password" required/>
            <?php echo $this->render('form/validation/error.phtml', ['element' => $element]); ?>
        </div>
        <div class="form-group mb-5 validated">
            <?php
            /** @var Element $element */
            $element = $form->get('confirm_new_password');
            ?>
            <input autocomplete="off" class="form-control h-auto form-control-solid py-4 px-8" name="confirm_new_password" placeholder="Confirm password" type="password" required/>
            <?php echo $this->render('form/validation/error.phtml', ['element' => $element]); ?>
        </div>
        <button class="btn btn-primary font-weight-bold px-9 py-4 my-3 mx-4"><?= $this->translate('Submit') ?></button>
    </form>
</div>

