<?php
/**
 * base.phtml
 * 
 * @since 23.12.2019
 * @author Alexej Kisselev <alexej.kisselev@gmail.com>
 */
?>
<!--begin::Footer-->
<div class="footer bg-white py-4 d-flex flex-lg-column " id="kt_footer"<?php echo devhelp(__FILE__) ?>>
    <!--begin::Container-->
    <div class=" container-fluid  d-flex flex-column flex-md-row align-items-center justify-content-between">
        <!--begin::Copyright-->
        <div class="text-dark order-2 order-md-1">
            <?php echo $this->render('app/footer') ?>
        </div>	
        <!--end::Copyright-->
    </div>
    <!--end::Container-->
</div>
<!-- end:: Footer -->