<?php
/**
 * File layout.phtml
 *
 * since: 23.01.2021
 * author: alexej@kisselev.de
 */

use Application\ModuleOptions;

/** @var ModuleOptions $moduleOptions */
$moduleOptions = $this->serviceManager()->get(ModuleOptions::class);
$name = $moduleOptions->getName();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">


<body topmargin="0" bottommargin="0" leftmargin="0" rightmargin="0" bgcolor="#ffffff" style="padding: 0; margin: 0;font-family: Helvetica, Arial, sans-serif;font-size: 12px">
<!--Header -->
<table width="100%" border="0" cellspacing="0" cellpadding="0" style="padding: 0; margin: 0">
    <thead>
    <tr>
        <td width="50%" style="width: 50%;background-color: #1e1e2d;"></td>
        <td width="600" valign="middle" style="background-color: #1e1e2d;color: white; padding: 15px 0;">
            <?php echo $this->render('email/header') ?>
        </td>
        <td width="50%" style="width: 50%;background-color: #1e1e2d;"></td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td></td>
        <td width="600" style="padding: 20px 0;">
            <?php echo $this->content ?>
        </td>
        <td></td>
    </tr>
    <tr>
        <td width="50%" style="background-color: #f3f6f9;"></td>
        <td width="600" style="color: #7E8299;background-color: #f3f6f9;padding: 20px 0;">
            <?php echo $this->render('email/footer') ?>
        </td>
        <td width="50%" style="background-color: #f3f6f9;"></td>
    </tr>
    <tr>
        <td width="50%" style="background-color: #1e1e2d;"></td>
        <td width="600" style="min-width: 600px;background-color: #1e1e2d;text-align: center;color: #7E8299;padding: 15px 0;font-size: 12px;">
            <?php
            $year = (new DateTime())->format('Y');
            if ($year !== '2021') {
                $year = ' - ' . $year;
            } else {
                $year = '';
            }
            ?>
            2021<?= $year ?> &copy; <?= $name ?>
        </td>
        <td width="50%" style="background-color: #1e1e2d;"></td>
    </tr>
    </tbody>
</table>
</body>
</html>
