<?php
    /**
     * Class ${NAME}
     * since: 01.07.2020
     * author: alexej@kisselev.de
     */
    $message = $this->message;
    if(empty($message)){
        return;
    }
    ?>

<div class="alert alert-custom alert-outline-danger fade show mb-5" role="alert">
    <div class="alert-icon">
        <i class="flaticon-warning"></i>
    </div>
    <div class="alert-text"><?= $message ?></div>
    <div class="alert-close">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">
                        <i class="ki ki-close"></i>
                    </span>
        </button>
    </div>
</div>
