<?php
/**
 * File button-back.phtml
 * since: 08.07.2020
 * author: alexej@kisselev.de
 */


$controller = $this->params('controller');
$action = $this->params('action');
$language = $this->params('language');

$text = 'Back';
$url = $this->history()->getLastUrlFor('list');
if (empty($url)) {
    $url = $this->url('default', ['language' => $language]);
}
?>
<p class="font-size-h3 text-muted font-weight-normal">
    <a class="btn btn-success" style="margin-right: 15px" href="<?php echo $url ?>">
        <i class="fa fa-chevron-left"></i> <?= $this->translate($text) ?>
    </a>
</p>