<?php
/**
 *
 * user-list.phtml
 *
 * @since 16.05.2017
 * @author Alexej Kisselev <alexej.kisselev@gmail.com>
 */

$resource = $this->params('controller');

if ($this->acl()->isAllowed(null, $resource, 'create')):
    $createUrl = $this->url('default/admin', ['action' => 'create', 'controller' => 'user']);
    ?>
    <a href="<?php echo $createUrl ?>" class="btn btn-secondary font-weight-bold btn-sm"<?php echo devhelp(__FILE__) ?>>
        <i class="fa fa-user-plus"></i> <?= $this->translate('Create new User') ?>
    </a>
<?php
endif;
