<?php
/**
 * recover-password.phtml
 *
 * @since 11.01.2021
 * @author Alexej Kisselev <alexej.kisselev@gmail.com>
 */
?>
<p class="style2" style="margin-bottom: 22px;line-height: 22px;font-size: 24px;color: #3f4254;font-family: Arial, sans-serif;">
    <?= $this->translate('Forgot your Password') ?>?

</p>
<p class="style5" style="margin-top: 0;margin-bottom: 22px;line-height: 18px;font-size: 13px;color: #3f4254;font-family: Helvetica, Arial, sans-serif;">
    <?= $this->translate("Don´t worry you are only human") ?> !
</p>
<hr class="light" style="color: #f3f6f9;">
<p class="style4" style="margin-bottom: 22px;line-height: 18px;font-size: 16px;color: #3f4254;font-family: Arial, sans-serif;font-weight: bold;">
    <?= $this->translate("To reset and create a new password") ?>:
</p>

<a class="btn blue" href="<?php echo $this->url ?>" style="color: #3699ff;text-decoration: none;"><?= $this->translate('CLICK HERE') ?></a>

<p class="style5" style="margin-bottom: 22px;line-height: 18px;font-size: 13px;color: #3f4254;font-family: Helvetica, Arial, sans-serif;">
    <?= $this->translate("This link is valid 24 hours and for one time use only") ?>
</p>