<?php
/**
 * base.phtml
 * 
 * @since 23.12.2019
 * @author Alexej Kisselev <alexej.kisselev@gmail.com>
 */
?>

<!--begin::Topbar-->
<div class="topbar">

    <!--[html-partial:include:{"file":"partials/_header/topbar/_search.html"}]/-->

    <!--[html-partial:include:{"file":"partials/_header/topbar/_notifications.html"}]/-->

    <!--[html-partial:include:{"file":"partials/_header/topbar/_quick-actions.html"}]/-->

    <!--[html-partial:include:{"file":"partials/_header/topbar/_my-cart.html"}]/-->

    <!--[html-partial:include:{"file":"partials/_header/topbar/_quick-panel.html"}]/-->

    <!--[html-partial:include:{"file":"partials/_header/topbar/_languages.html"}]/-->

    <!--[html-partial:include:{"file":"partials/_header/topbar/_user.html"}]/-->
    <?php echo $this->render('layout/header/topbar/user'); ?> 

</div>

<!-- end:: Header Topbar -->