<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 *
 */
?>

<div class="card col-lg-6 col-md-6 col-sm-12 col-">
    <div class="card-header card-transparent">
        <h2><?= $this->translate('Product Information Management') ?></h2>
    </div>
    <div class="card-body">
        <p>
            A Product Information Management (PIM) solution provides a single place to collect, manage, and enrich your product information, create a product catalog.
            A PIM solution makes it faster and easier to create and deliver compelling product experiences.
        </p>

        <!--                <a class="btn btn-primary" href="https://getlaminas.org/" target="_blank">Laminas Project Portal &raquo;</a>-->
    </div>
</div>


