<?php

/**
 * header.phtml
 *
 * @since 11.01.2021
 * @author Alexej Kisselev <alexej.kisselev@gmail.com>
 */

use Application\ModuleOptions;

/** @var ModuleOptions $moduleOptions */
$moduleOptions = $this->serviceManager()->get(ModuleOptions::class);
$name = $moduleOptions->getName();
?>

<!--
---------------------------
Start Footer Contact Module
---------------------------
 -->
<table width="100%" border="0" cellspacing="0" cellpadding="0" align="center" class="lightbg" style="background-color: #f3f6f9;">
    <tr>
        <td align="center">
            <!--Logo and Contact Info-->
            <table width="600" border="0" cellspacing="0" cellpadding="0" align="center" class="lightbg gray style5"
                   style="font-size: 13px;line-height: 18px;font-family: Helvetica, Arial, sans-serif;color: #7E8299;background-color: #f3f6f9;">
                <tr>
                    <td align="left" valign="middle" class="gray" style="color: #7E8299;">
                        <?php echo $this->translate('If you need any help, please feel free to contact your account manager') ?>.
                    </td>
                </tr>
                <tr height="10">
                    <td></td>
                </tr>
                <tr>
                    <td>
                        <br>
                        <?php echo $this->translate('Best regards') ?>,<br>
                        <?php echo $this->translate("$name Support Team") ?>
                    </td>
                </tr>
                <tr height="20">
                    <td></td>
                </tr>
                <tr>
                    <td class="style6" style="font-size: 12px;line-height: 16px;font-family: Helvetica, Arial, sans-serif;">
                        <br>
                        <?php echo $this->translate('This is a no-reply e mail') ?>.
                        <?php echo $this->translate('If you do not want to receive this kind of mails, please contact your AM or disable it in our management system') ?>.
                    </td>
                </tr>
            </table>
            <!--End Logo and Contact Info-->
        </td>
    </tr>
</table>
<!--
---------------------------
End Footer Contact Module
---------------------------
 -->
